# golangci-lint configuration (v2.x)
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - misspell
    - unconvert
    - gocritic
    - revive
    - gosec
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: UK
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - hugeParam
    gosec:
      excludes:
        - G304

formatters:
  enable:
    - gofmt
    - goimports
